### ISSUE TITLE
Add visual marking safe of use pins

### ISSUE THREAD

**Issue by bato3** [atomic14/esp32-s3-pinouts#4]
I think it is worth following the example of [LastMinuteEngineers.com](https://lastminuteengineers.com/esp32-pinout-reference/), who explained _ESP32 devkit v1_ quite thoroughly. And there I really like the section: "Which ESP32 GPIOs are safe to use?", where they added icons showing which pins to avoid and which to watch out for.

![image](https://github.com/atomic14/esp32-s3-pinouts/assets/11570/b0d7df78-fd49-460d-8100-bffdbcd71e26)

Should be marked:
- Not allowed pins,
- Strapping pins
- Not recommended pins (PSRAM, UART, JTAG,...)
- Power Up Glitches pins

**Comment by cgreening** [comment]
Closed by #7e48c070700df781cb6adb3540c3e72a24d904b9
